# Generated by Django 5.2 on 2025-04-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AddField(
            model_name='review',
            name='cons',
            field=models.TextField(blank=True, verbose_name='Минусы'),
        ),
        migrations.AddField(
            model_name='review',
            name='pros',
            field=models.TextField(blank=True, verbose_name='Плюсы'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 звёзд'), (2, '2 звёзды'), (3, '3 звёзды'), (4, '4 звёзды'), (5, '5 звёзды')], verbose_name='Оценка'),
        ),
    ]
