# Generated by Django 5.2 on 2025-04-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remove_review_comment_review_cons_review_pros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors_photos/', verbose_name='Фотография'),
        ),
    ]
